{% set version = "0.0.1" %}

package:
  name: transannot 
  version: {{ version }}

build:
  number: 0

source:
  git_url: https://github.com/mariia-zelenskaia/transannot.git
  git_rev: {{ version }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - perl
    - gawk
    - zlib
    - bzip2
  run:
    - gawk
    - zlib
    - bzip2

test:
  commands:
    - transannot > /dev/null

about:
  home: https://github.com/mariia-zelenskaia/transannot
  license: GPLv3
  summary: "TransAnnot - a fast and light transcriptome annotation pipeline" 

extra:
  skip-lints:
    - uses_vcs_url
    - missing_hash
  identifiers:
    - biotools:transannot
